version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: expense_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - expense-net

  redis:
    image: redis:alpine
    container_name: expense_redis
    ports:
      - "6379:6379"
    networks:
      - expense-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: expense_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     
      - "15672:15672"  
    networks:
      - expense-net

volumes:
  pgdata:

networks:
  expense-net:
    driver: bridge
